# Generated by Django 4.1.7 on 2023-06-22 07:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='NewRoot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=150)),
                ('root', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=150)),
                ('endings', models.CharField(max_length=150)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Жаңы негиз',
                'verbose_name_plural': 'Жаңы негиздер',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=150)),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тегдер',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_of_speech', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('tag', models.ManyToManyField(to='analyzer.tags')),
            ],
            options={
                'verbose_name': 'Сөз түркүмү',
                'verbose_name_plural': 'Сөз түркүмдөрү',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Endings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('tagid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.tags')),
            ],
            options={
                'verbose_name': 'Мүчө',
                'verbose_name_plural': 'Мүчөлөр',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AllRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=150)),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.partofspeech')),
                ('tag', models.ManyToManyField(blank=True, to='analyzer.tags')),
            ],
            options={
                'verbose_name': 'Негиз',
                'verbose_name_plural': 'Негиздер',
                'ordering': ['id'],
            },
        ),
    ]
