# Generated by Django 4.1.7 on 2023-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newroot',
            name='endings',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
