# Generated by Django 4.1.7 on 2023-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_alter_newroot_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newroot',
            name='is_done',
            field=models.BooleanField(),
        ),
    ]
